USE [master]
GO

/****** Object:  Database [Civilization]    Script Date: 18.02.2024 23:43:32 ******/
CREATE DATABASE [Civilization]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Civilization', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Civilization.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Civilization_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Civilization_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Civilization].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Civilization] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Civilization] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Civilization] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Civilization] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Civilization] SET ARITHABORT OFF 
GO

ALTER DATABASE [Civilization] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Civilization] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Civilization] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Civilization] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Civilization] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Civilization] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Civilization] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Civilization] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Civilization] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Civilization] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Civilization] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Civilization] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Civilization] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Civilization] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Civilization] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Civilization] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Civilization] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Civilization] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Civilization] SET  MULTI_USER 
GO

ALTER DATABASE [Civilization] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Civilization] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Civilization] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Civilization] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Civilization] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Civilization] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Civilization] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Civilization] SET  READ_WRITE 
GO


